# used by Hyde
title: InfoSec101
email: infosec101@fabian-lischka.de
tagline: "InfoSec 101 for (non-IT) Professionals"
description: "An introduction to Information Security 101 for Journalists, 
Doctors, Lawyers, and other (non-IT) Professionals"

twitter_username: false
github_username: fabianlischka

github:
  repo:           https://github.com/fabianlischka/InfoSec101

author:
  name:           'Fabian R Lischka'
#  url:            https://www.something.de


baseurl:           'http://infosec101.de'
# url:               'http://infosec101.de'


# Build settings
exclude: ["old/","*.numbers", "vendor"]
markdown: redcarpet
highlighter:      pygments

plugins:
    - jekyll-sitemap

# Permalinks
permalink:        pretty
relative_permalinks: false


